"""
KiCad File Format Module

Parsers, filters, extractors, and utilities for KiCad files
(.kicad_pcb, .kicad_sch, .kicad_sym, .kicad_mod, .kicad_wks, etc.).

The library exposes two complementary tracks:

OOP track — typed dataclasses for callers that need to read geometry
or topology (e.g. layout-to-neutral-model converters, SVG render):

    >>> from kicad_monkey import KiCadPcb
    >>> pcb = KiCadPcb.from_file("board.kicad_pcb")
    >>> pcb.footprints[0].reference
    >>> pcb.to_file("output.kicad_pcb")

    >>> from kicad_monkey import KiCadFootprint, KiCadSchematic, KiCadSymbolLib
    >>> sch = KiCadSchematic.from_file("design.kicad_sch")
    >>> lib = KiCadSymbolLib.from_file("library.kicad_sym")
    >>> fp  = KiCadFootprint.from_file("resistor.kicad_mod")

S-Expression track — parse → mutate → re-emit for filter / extract
use cases that don't need the typed model. Round-trip is byte-stable
on the upstream-QA corpus, so pass-through is a first-class fallback
for unknown / uninteresting children:

    >>> from kicad_monkey import parse_sexp, format_sexp
    >>> from kicad_monkey import find_element, find_all_elements, get_value
    >>> sexp = parse_sexp(open("board.kicad_pcb").read())
    >>> for fp_sexp in find_all_elements(sexp, "footprint"):
    ...     ref = get_value(find_element(fp_sexp, "property"), "Reference")

File-level filters compose well with the s-expression track:

    >>> from kicad_monkey import KiCadFilterPipeline
    >>> KiCadFilterPipeline().filter_footprint(in_path, out_path)

Or call individual filter functions directly on a parsed s-expression:

    >>> from kicad_monkey import sym_filter__clear_property_values
    >>> filtered = sym_filter__clear_property_values(parse_sexp(text))

Extractors pull embedded artifacts out without loading the full OOP
model:

    >>> from kicad_monkey import (
    ...     extract_footprints_from_pcb,
    ...     extract_symbols_from_text,
    ...     extract_step_from_footprint,
    ... )

Project Utilities:
    >>> from kicad_monkey import read_kicad_pro_parameters
    >>> params = read_kicad_pro_parameters("project.kicad_pro")

Symbol Library Operations (class methods):
    >>> lib = KiCadSymbolLib.from_directory('symbols/', recursive=True)
    >>> lib.to_file('merged.kicad_sym')
    >>> lib.split_to_directory('output/')

The two extractor modules ``kicad_symbol_extractor`` and
``kicad_sch_extractor`` both define a function called
``extract_symbols_from_schematic`` with different return contracts
(parsed-sexpr-tuples vs. write-to-disk). Import them via the explicit
module path when you need a specific one:

    >>> from kicad_monkey.kicad_symbol_extractor import extract_symbols_from_schematic
    >>> from kicad_monkey.kicad_sch_extractor   import extract_symbols_from_schematic

NOTE: Heavy modules (parsers, filters, extractors, geometry utilities)
are lazy-loaded on first access to keep import times fast. The
s-expression parser and read helpers are always available.
"""

from __future__ import annotations

from importlib import import_module
from typing import Any

from ._version import Version, __version__, parse_version, version

# Self-contained S-expression parser (no external dependencies)
from .kicad_sexpr import (
    PARSER_DIALECT_EXCEPTIONS,
    ParserDialectException,
    QuotedString,
    SexpRoundtripResult,
    SexpSpan,
    SexprBuilder,
    SexprDialectError,
    SexprError,
    SexprItem,
    SexprLexError,
    SexprTreeError,
    build_sexp,
    debug_dump_tokens,
    format_sexp,
    parse_sexp,
    parse_sexp_with_spans,
    roundtrip_sexp_text,
    string_to_sexp,
    validate_bare_string,
)

__all__ = [
    # Package metadata
    "__version__",
    "Version",
    "parse_version",
    "version",
    # S-expression parsing
    "parse_sexp",
    "build_sexp",
    "format_sexp",
    "SexprItem",
    "string_to_sexp",
    "validate_bare_string",
    "QuotedString",
    "SexprError",
    "SexprLexError",
    "SexprTreeError",
    "SexprDialectError",
    "SexprBuilder",
    "SexpRoundtripResult",
    "roundtrip_sexp_text",
    "PARSER_DIALECT_EXCEPTIONS",
    "ParserDialectException",
    "SexpSpan",
    "parse_sexp_with_spans",
    "debug_dump_tokens",
    # S-expression read helpers (kicad_base — lazy loaded)
    "find_element",
    "find_all_elements",
    "get_value",
    "get_values",
    "has_flag",
    "parse_maybe_absent_bool",
    "unquote_string",
    # S-expression mutation primitives (kicad_base — lazy loaded)
    "replace_element",
    "remove_element",
    "remove_all_elements",
    "set_value",
    "walk",
    "find_path",
    "transform_descendants",
    # Environment and filter framework entry points (lazy loaded)
    "KiCadEnvironment",
    "KiCadFilterPipeline",
    "KiCadNameIndex",
    # Filter framework — formatting helpers (lazy loaded)
    "format_kicad_sexp",
    # Filter framework — individual filters (lazy loaded)
    "fp_filter__add_fab_bounding_orthogonal_convex",
    "fp_filter__clean_fab",
    "fp_filter__clean_layers",
    "fp_filter__fix_fp_text_font_to_arial",
    "fp_filter__fix_zero_sized_pads",
    "fp_filter__normalized_embedded_model_naming",
    "fp_filter__orthographic_projection_outline",
    "pcb_filter__process_embedded_footprints",
    "pcb_filter__reset_layer_user_names",
    "sch_filter__remove_altium_value_property",
    "sym_filter__clear_property_values",
    "sym_filter__remove_nonstandard_properties",
    "sym_filter__standardize_reference_value_fonts",
    # Extractors — footprint (lazy loaded)
    "extract_footprints_from_text",
    "extract_footprints_from_pcb",
    "extract_footprints_from_project",
    # Extractors — symbol (lazy loaded; parses sexpr)
    "extract_symbols_from_text",
    "create_symbol_file_content",
    # Extractors — schematic file-level (lazy loaded; writes files)
    "list_symbols_in_schematic",
    # Extractors — STEP (lazy loaded)
    "find_embedded_step_data",
    "extract_step_from_text",
    "extract_step_from_footprint",
    "extract_step_from_directory",
    "view_step_file",
    # New OOP model - PCB (lazy loaded)
    "KiCadPcb",
    "from_kicad_pcb",
    "to_kicad_pcb",
    # New OOP model - Footprint (lazy loaded)
    "KiCadFootprint",
    "from_kicad_mod",
    "to_kicad_mod",
    # New OOP model - Symbol Library (lazy loaded)
    "KiCadSymbolLib",
    "LibSymbol",
    "LibSubSymbol",
    "SymProperty",
    "SymPin",
    "SymRectangle",
    "SymCircle",
    "SymArc",
    "SymPolyline",
    "SymBezier",
    "SymText",
    "SymTextBox",
    "SymFill",
    "SymFillType",
    "KiCadObjectCollection",
    # Shared KiCad defaults (lazy loaded)
    "KICAD_DEFAULT_BOARD_THICKNESS_MM",
    "KICAD_DEFAULT_PAPER",
    "KICAD_DEFAULT_PIN_NAME_OFFSET_MM",
    "KICAD_DEFAULT_SHEET_HEIGHT_MM",
    "KICAD_DEFAULT_SHEET_WIDTH_MM",
    "KICAD_DEFAULT_TEXT_SIZE_MM",
    "KICAD_FOOTPRINT_FILE_VERSION",
    "KICAD_FOOTPRINT_GENERATOR",
    "KICAD_GENERATOR_VERSION",
    "KICAD_PCB_FILE_VERSION",
    "KICAD_PCB_GENERATOR",
    "KICAD_SCHEMATIC_FILE_VERSION",
    "KICAD_SCHEMATIC_GENERATOR",
    "KICAD_SYMBOL_LIB_FILE_VERSION",
    "KICAD_SYMBOL_LIB_GENERATOR",
    # Shared primitives (lazy loaded)
    "Stroke",
    "Font",
    "Effects",
    "Justify",
    "RenderCacheContour",
    "RenderCachePolygon",
    "RenderCache",
    "RenderCacheRequest",
    "RenderCacheResolver",
    "RenderCacheResult",
    "RenderCacheSource",
    "RenderCacheValidation",
    "board_text_variables",
    "ensure_render_cache",
    "footprint_text_variables",
    "generate_render_cache_from_text_params",
    "render_cache_exterior_polygons",
    "render_cache_request_for_board_text",
    "render_cache_request_for_dimension_text",
    "render_cache_request_for_footprint_property",
    "render_cache_request_for_footprint_text",
    "render_cache_request_for_footprint_text_box",
    "render_cache_request_for_table_cell",
    "substitute_text_variables",
    "table_cell_text_variables",
    "KiCadRenderCacheOracleError",
    "RenderCacheComparison",
    "RenderCacheCoverageObject",
    "RenderCacheCoverageSummary",
    "RenderCacheEntrySetComparison",
    "RenderCacheOracleEntry",
    "RenderCacheOracleResult",
    "build_render_cache_coverage_report",
    "build_render_cache_coverage_report_from_pcb",
    "collect_render_cache_requests_from_pcb",
    "compare_render_cache_entries",
    "compare_render_cache_entry_sets",
    "compare_render_caches",
    "extract_render_cache_entries_from_pcb",
    "render_cache_coverage_markdown",
    "run_kicad_pcb_render_cache_save_oracle",
    "summarize_render_cache_entries",
    "summarize_render_cache_requests",
    "strip_render_cache_blocks",
    "strip_render_cache_blocks_from_sexp",
    "write_render_cache_coverage_report",
    # Schematic enums (lazy loaded)
    "PinElectricalType",
    "PinGraphicStyle",
    "LabelShape",
    "StandardPropertyKey",
    "StandardSheetPropertyKey",
    "PropertyId",
    # New OOP model - Schematic Document (lazy loaded)
    "KiCadSchematic",
    "SchSymbol",
    "SchWire",
    "SchBus",
    "SchBusEntry",
    "SchJunction",
    "SchNoConnect",
    "SchLabel",
    "SchGlobalLabel",
    "SchHierarchicalLabel",
    "SchSheet",
    "SchTextBox",
    "TitleBlock",
    "PaperSize",
    # New OOP model - Worksheet (lazy loaded)
    "KiCadWorksheet",
    "WksSetup",
    "WksLine",
    "WksRect",
    "WksPolygon",
    "WksTbText",
    "WksBitmap",
    "WksCorner",
    "WksPoint",
    # OOP element classes (lazy loaded)
    "Footprint",
    "Pad",
    "FpText",
    "FpTextBox",
    "FpLine",
    "FpPoly",
    "Zone",
    "Segment",
    "Via",
    "Arc",
    "GrText",
    "GrLine",
    "GrRect",
    "GrArc",
    "GrCircle",
    "GrPoly",
    "GrCurve",
    "GrTextBox",
    "Layer",
    "Net",
    "NetRef",
    "OutlineCarrier",
    "BarcodeMargins",
    "Barcode",
    "DrillLayerSpan",
    "DrillProps",
    "PostMachiningProps",
    "ZoneLayerConnections",
    "PadNameGroup",
    "BoardVariant",
    "FootprintVariantField",
    "FootprintVariant",
    "FootprintPlacement",
    "ComponentClassRef",
    "GeneratedProperty",
    "GeneratedObject",
    "KiCadProject",
    "KiCadProjectBoardDesignSettings",
    "KiCadProjectDiffPairDimensions",
    "KiCadProjectNetClass",
    "KiCadProjectNetClassPattern",
    "KiCadProjectNetSettings",
    "KiCadProjectSidecar",
    "KiCadProjectTuningPatternDefaults",
    "KiCadProjectTuningPatternSettings",
    "ProjectVariant",
    "find_adjacent_kicad_project_path",
    # Variant model (lazy loaded)
    "AssemblyComponent",
    "EffectiveFootprintProperties",
    "EffectiveSymbolProperties",
    "VariantCatalog",
    "VariantOverride",
    "assemble",
    "collect_footprint_overrides",
    "collect_symbol_overrides",
    "resolve_footprint",
    "resolve_symbol",
    # Geometry utilities (lazy loaded)
    "BoundingBox",
    "SvgRenderContext",
    "rotate_point",
    # Symbol SVG rendering (lazy loaded)
    "SymbolTheme",
    "SymbolSvgContext",
    "SymbolRenderOptions",
    "render_symbol_svg",
    "render_library_svg",
    # Schematic SVG rendering (lazy loaded)
    "SchematicTheme",
    "SchematicSvgContext",
    "SchematicRenderOptions",
    "render_schematic_svg",
    "render_schematic_to_file",
    # Project utilities (lazy loaded)
    "read_kicad_pro_parameters",
    "make_kicad_httplib",
    "setup_kicad_preferences",
    # Plotter IR (lazy loaded)
    "KICAD_PLOTTER_IR_SCHEMA",
    "KiCadFillType",
    "KiCadHorizAlign",
    "KiCadLineStyle",
    "KiCadPenAction",
    "KiCadPlotterBounds",
    "KiCadPlotterDocument",
    "KiCadPlotterOp",
    "KiCadPlotterOpKind",
    "KiCadPlotterRecord",
    "KiCadVertAlign",
    "make_brush",
    "make_font",
    "make_pen",
    "styled_plotter_op",
    # SVG primitive layer (lazy loaded)
    "KiCadJunctionZOrder",
    "KiCadSvgRenderContext",
    "KiCadSvgRenderOptions",
    "KiCadSvgRenderProfile",
    "KiCadVariantDimMode",
    "fmt_user_number",
    "svg_arc",
    "svg_bezier",
    "svg_circle",
    "svg_document",
    "svg_ellipse",
    "svg_group",
    "svg_line",
    "svg_path",
    "svg_polygon",
    "svg_polyline",
    "svg_rect",
    "svg_text",
    "svg_text_or_poly",
    "svg_text_poly",
    "SCHEMATIC_SVG_BLACK_AND_WHITE_ROLE_COLORS",
    "SCHEMATIC_SVG_COLOR_ROLES",
    "SCHEMATIC_SVG_ROLE_COLORS",
    "normalize_schematic_svg_color_role",
    "schematic_svg_role_color",
    "schematic_svg_role_color_overrides",
    "KiCadSvgPreferenceTheme",
    "load_kicad_svg_preference_theme",
    "schematic_svg_options_from_preferences",
    "symbol_theme_from_preferences",
    # LibSymbol → IR converter (lazy loaded)
    "arc_to_op",
    "bezier_to_op",
    "circle_to_op",
    "lib_symbol_to_ir",
    "mm_to_nm",
    "pin_to_ops",
    "polyline_to_op",
    "rectangle_to_op",
    "rgba_to_hex",
    "stroke_type_to_line_style",
    "stroke_width_nm",
    "subsymbol_to_record",
    "sym_fill_to_kicad_fill",
    "text_to_op",
    "y_to_ir",
    # Schematic → IR converter (lazy loaded)
    "DEFAULT_BUS_WIDTH_MM",
    "DEFAULT_JUNCTION_DIAMETER_MM",
    "DEFAULT_LABEL_SIZE_RATIO",
    "DEFAULT_NO_CONNECT_HALF_MM",
    "DEFAULT_TEXT_SIZE_MM",
    "DEFAULT_WIRE_WIDTH_MM",
    "bus_entry_to_op",
    "bus_to_op",
    "global_label_decoration_to_op",
    "global_label_to_op",
    "hierarchical_label_decoration_to_op",
    "hierarchical_label_to_op",
    "junction_to_op",
    "label_to_op",
    "no_connect_to_ops",
    "paper_size_to_nm",
    "sch_text_to_op",
    "schematic_arc_to_ops",
    "schematic_bezier_to_ops",
    "schematic_circle_to_ops",
    "schematic_image_to_op",
    "schematic_polyline_to_ops",
    "schematic_rectangle_to_ops",
    "schematic_to_ir",
    "sheet_background_to_op",
    "sheet_outline_to_op",
    "sheet_pin_decoration_to_op",
    "sheet_pin_to_op",
    "sheet_property_to_op",
    "symbol_property_to_op",
    "text_box_outline_to_op",
    "text_box_to_ops",
    "wire_to_op",
    # IR → SVG renderer (lazy loaded)
    "render_ir_to_svg",
    "render_op",
    "render_record",
    "render_records",
    # Recorder JSON loader (lazy loaded)
    "KICAD_PLOTTER_RECORDER_SCHEMA",
    "load_recorder_dict",
    "load_recorder_file",
    "normalise_recorder_op_units",
    "translate_recorder_canvas",
    "translate_recorder_op",
    # Recorder drift report (lazy loaded)
    "KICAD_RECORDER_DRIFT_SCHEMA",
    "RecorderDriftReport",
    "compute_recorder_drift",
    # Stroked-text fold (lazy loaded)
    "STROKED_TEXT_FOLD_KIND",
    "STROKED_TEXT_FOLD_MIN_POINTS",
    "STROKED_TEXT_FOLD_MIN_RUN",
    "fold_recorder_document",
    "fold_stroked_text_runs",
    "is_stroked_text_glyph",
    # Op-by-op equivalence diff (lazy loaded)
    "KICAD_OP_EQUIVALENCE_SCHEMA",
    "MATCH_STRATEGY_BY_KIND",
    "MATCH_STRATEGY_POSITIONAL",
    "MATCH_STRATEGY_WINDOWED_BY_KIND",
    "MATCH_WINDOW_UNBOUNDED",
    "KiCadOpDivergence",
    "OpEquivalenceReport",
    "compute_op_equivalence",
    # Plotter-IR coordinate transform (lazy loaded)
    "KiCadPlotterTransform2D",
    "apply_transform_to_op",
    "apply_transform_to_ops",
    "transform_orient",
    "transform_point",
    # Drawing sheet emitter (lazy loaded)
    "DEFAULT_KICAD_WKS",
    "drawing_sheet_to_ops",
    "expand_format_codes",
    "load_default_drawing_sheet",
    # Design aggregator (lazy loaded)
    "KiCadDesign",
    "KiCadSchematicInstance",
    # Footprint → IR converter (lazy loaded)
    "footprint_to_ir",
    "footprint_to_record",
    "fp_arc_to_op",
    "fp_circle_to_op",
    "fp_fill_to_kicad_fill",
    "fp_line_to_op",
    "fp_poly_to_op",
    "fp_rect_to_op",
    "fp_text_box_to_ops",
    "fp_text_to_op",
    "pad_drill_to_ops",
    "pad_to_ops",
    "property_to_op",
    # Variant overlay (lazy loaded)
    "KiCadVariantOverlayPolicy",
    "VARIANT_STATE_ACTIVE",
    "VARIANT_STATE_DIMMED",
    "VARIANT_STATE_KEY",
    "annotate_record_variant_state",
    "apply_variant_overlay",
    "compute_record_variant_state",
    # PCB → IR converter (lazy loaded)
    "pcb_to_ir",
    "gr_line_to_op",
    "gr_line_to_record",
    "gr_arc_to_op",
    "gr_arc_to_record",
    "gr_circle_to_op",
    "gr_circle_to_record",
    "gr_rect_to_op",
    "gr_rect_to_record",
    "gr_poly_to_op",
    "gr_poly_to_record",
    "gr_curve_to_op",
    "gr_curve_to_record",
    "gr_text_to_op",
    "gr_text_to_record",
    "gr_text_box_to_ops",
    "gr_text_box_to_record",
    "track_segment_to_op",
    "track_segment_to_record",
    "track_arc_to_op",
    "track_arc_to_record",
    "via_drill_to_op",
    "via_to_op",
    "via_to_record",
    "zone_filled_polygon_to_op",
    "zone_to_record",
    "pcb_footprint_to_record",
    # PCB IR → SVG wrapper (lazy loaded)
    "render_pcb_ir_to_svg",
    # Schematic connectivity primitives (lazy loaded)
    "SCH_IU_PER_MM",
    "snap_mm_to_iu",
    "iu_key_to_mm",
    "compute_pin_position",
    "iter_symbol_pins",
    "CoordinateIndex",
    "ConnectivityGraph",
    "detect_no_connects",
    # Bus label expansion (lazy loaded)
    "is_bus_label",
    "parse_bus_vector",
    "parse_bus_group",
    "expand_bus_label",
    # Netlist model + single-sheet compiler (lazy loaded)
    "KiCadDriverPriority",
    "KiCadDriverKind",
    "KiCadPinType",
    "KiCadNetlistTerminal",
    "KiCadNetEndpoint",
    "KiCadNet",
    "KiCadNetlistComponent",
    "KiCadLibPart",
    "KiCadLibPartPin",
    "KiCadDesignSheet",
    "KiCadDesignMetadata",
    "KiCadNetlist",
    "Subgraph",
    "compile_sheet_subgraphs",
    "compile_sheet_netlist",
    "name_net",
    # Multi-sheet netlist compile (lazy loaded)
    "CompiledSheet",
    "compile_design_subgraphs",
    "merge_design_nets",
    "compile_design_netlist",
    "collect_design_components",
    "collect_design_libparts",
    # KiCad-format netlist emit (lazy loaded)
    "KICAD_NETLIST_VERSION",
    "to_kicad_sexpr",
]


_LAZY_EXPORT_MODULES: dict[str, str] = {
    'find_element': 'kicad_base',
    'find_all_elements': 'kicad_base',
    'get_value': 'kicad_base',
    'get_values': 'kicad_base',
    'has_flag': 'kicad_base',
    'parse_maybe_absent_bool': 'kicad_base',
    'unquote_string': 'kicad_base',
    'replace_element': 'kicad_base',
    'remove_element': 'kicad_base',
    'remove_all_elements': 'kicad_base',
    'set_value': 'kicad_base',
    'walk': 'kicad_base',
    'find_path': 'kicad_base',
    'transform_descendants': 'kicad_base',
    'KiCadEnvironment': 'kicad_environment',
    'KiCadFilterPipeline': 'kicad_filter_core',
    'KiCadNameIndex': 'kicad_name_index',
    'format_kicad_sexp': 'kicad_filter_core',
    'fp_filter__add_fab_bounding_orthogonal_convex': 'kicad_filter_footprint',
    'fp_filter__clean_fab': 'kicad_filter_footprint',
    'fp_filter__clean_layers': 'kicad_filter_footprint',
    'fp_filter__fix_fp_text_font_to_arial': 'kicad_filter_footprint',
    'fp_filter__fix_zero_sized_pads': 'kicad_filter_footprint',
    'fp_filter__normalized_embedded_model_naming': 'kicad_filter_footprint',
    'fp_filter__orthographic_projection_outline': 'kicad_filter_footprint',
    'pcb_filter__process_embedded_footprints': 'kicad_filter_pcb',
    'pcb_filter__reset_layer_user_names': 'kicad_filter_pcb',
    'sch_filter__remove_altium_value_property': 'kicad_filter_schematic',
    'sym_filter__clear_property_values': 'kicad_filter_symbol',
    'sym_filter__remove_nonstandard_properties': 'kicad_filter_symbol',
    'sym_filter__standardize_reference_value_fonts': 'kicad_filter_symbol',
    'extract_footprints_from_text': 'kicad_footprint_extractor',
    'extract_footprints_from_pcb': 'kicad_footprint_extractor',
    'extract_footprints_from_project': 'kicad_footprint_extractor',
    'extract_symbols_from_text': 'kicad_symbol_extractor',
    'create_symbol_file_content': 'kicad_symbol_extractor',
    'list_symbols_in_schematic': 'kicad_sch_extractor',
    'find_embedded_step_data': 'kicad_step_extractor',
    'extract_step_from_text': 'kicad_step_extractor',
    'extract_step_from_footprint': 'kicad_step_extractor',
    'extract_step_from_directory': 'kicad_step_extractor',
    'view_step_file': 'kicad_step_extractor',
    'KiCadPcb': 'kicad_pcb',
    'from_kicad_pcb': 'kicad_pcb',
    'to_kicad_pcb': 'kicad_pcb',
    'KiCadFootprint': 'kicad_footprint',
    'from_kicad_mod': 'kicad_footprint',
    'to_kicad_mod': 'kicad_footprint',
    'KiCadSymbolLib': 'kicad_symbol_lib',
    'LibSymbol': 'kicad_lib_symbol',
    'LibSubSymbol': 'kicad_lib_subsymbol',
    'SymProperty': 'kicad_sym_property',
    'SymPin': 'kicad_sym_pin',
    'SymRectangle': 'kicad_sym_rectangle',
    'SymCircle': 'kicad_sym_circle',
    'SymArc': 'kicad_sym_arc',
    'SymPolyline': 'kicad_sym_polyline',
    'SymBezier': 'kicad_sym_bezier',
    'SymText': 'kicad_sym_text',
    'SymTextBox': 'kicad_sym_text_box',
    'SymFill': 'kicad_sym_rectangle',
    'SymFillType': 'kicad_sym_rectangle',
    'KiCadObjectCollection': 'kicad_object_collection',
    'KICAD_DEFAULT_BOARD_THICKNESS_MM': 'kicad_defaults',
    'KICAD_DEFAULT_PAPER': 'kicad_defaults',
    'KICAD_DEFAULT_PIN_NAME_OFFSET_MM': 'kicad_defaults',
    'KICAD_DEFAULT_SHEET_HEIGHT_MM': 'kicad_defaults',
    'KICAD_DEFAULT_SHEET_WIDTH_MM': 'kicad_defaults',
    'KICAD_DEFAULT_TEXT_SIZE_MM': 'kicad_defaults',
    'KICAD_FOOTPRINT_FILE_VERSION': 'kicad_defaults',
    'KICAD_FOOTPRINT_GENERATOR': 'kicad_defaults',
    'KICAD_GENERATOR_VERSION': 'kicad_defaults',
    'KICAD_PCB_FILE_VERSION': 'kicad_defaults',
    'KICAD_PCB_GENERATOR': 'kicad_defaults',
    'KICAD_SCHEMATIC_FILE_VERSION': 'kicad_defaults',
    'KICAD_SCHEMATIC_GENERATOR': 'kicad_defaults',
    'KICAD_SYMBOL_LIB_FILE_VERSION': 'kicad_defaults',
    'KICAD_SYMBOL_LIB_GENERATOR': 'kicad_defaults',
    'Stroke': 'kicad_primitives',
    'Font': 'kicad_primitives',
    'Effects': 'kicad_primitives',
    'Justify': 'kicad_primitives',
    'RenderCacheContour': 'kicad_primitives',
    'RenderCachePolygon': 'kicad_primitives',
    'RenderCache': 'kicad_primitives',
    'RenderCacheRequest': 'kicad_render_cache',
    'RenderCacheResolver': 'kicad_render_cache',
    'RenderCacheResult': 'kicad_render_cache',
    'RenderCacheSource': 'kicad_render_cache',
    'RenderCacheValidation': 'kicad_render_cache',
    'board_text_variables': 'kicad_text_variables',
    'ensure_render_cache': 'kicad_render_cache',
    'footprint_text_variables': 'kicad_text_variables',
    'generate_render_cache_from_text_params': 'kicad_render_cache',
    'render_cache_exterior_polygons': 'kicad_render_cache',
    'render_cache_request_for_board_text': 'kicad_render_cache',
    'render_cache_request_for_dimension_text': 'kicad_render_cache',
    'render_cache_request_for_footprint_property': 'kicad_render_cache',
    'render_cache_request_for_footprint_text': 'kicad_render_cache',
    'render_cache_request_for_footprint_text_box': 'kicad_render_cache',
    'render_cache_request_for_table_cell': 'kicad_render_cache',
    'substitute_text_variables': 'kicad_text_variables',
    'table_cell_text_variables': 'kicad_text_variables',
    'KiCadRenderCacheOracleError': 'kicad_render_cache_oracle',
    'RenderCacheComparison': 'kicad_render_cache_oracle',
    'RenderCacheCoverageObject': 'kicad_render_cache_oracle',
    'RenderCacheCoverageSummary': 'kicad_render_cache_oracle',
    'RenderCacheEntrySetComparison': 'kicad_render_cache_oracle',
    'RenderCacheOracleEntry': 'kicad_render_cache_oracle',
    'RenderCacheOracleResult': 'kicad_render_cache_oracle',
    'build_render_cache_coverage_report': 'kicad_render_cache_oracle',
    'build_render_cache_coverage_report_from_pcb': 'kicad_render_cache_oracle',
    'collect_render_cache_requests_from_pcb': 'kicad_render_cache_oracle',
    'compare_render_cache_entries': 'kicad_render_cache_oracle',
    'compare_render_cache_entry_sets': 'kicad_render_cache_oracle',
    'compare_render_caches': 'kicad_render_cache_oracle',
    'extract_render_cache_entries_from_pcb': 'kicad_render_cache_oracle',
    'render_cache_coverage_markdown': 'kicad_render_cache_oracle',
    'run_kicad_pcb_render_cache_save_oracle': 'kicad_render_cache_oracle',
    'summarize_render_cache_entries': 'kicad_render_cache_oracle',
    'summarize_render_cache_requests': 'kicad_render_cache_oracle',
    'strip_render_cache_blocks': 'kicad_render_cache_oracle',
    'strip_render_cache_blocks_from_sexp': 'kicad_render_cache_oracle',
    'write_render_cache_coverage_report': 'kicad_render_cache_oracle',
    'PinElectricalType': 'kicad_sch_enums',
    'PinGraphicStyle': 'kicad_sch_enums',
    'LabelShape': 'kicad_sch_enums',
    'StandardPropertyKey': 'kicad_sch_enums',
    'StandardSheetPropertyKey': 'kicad_sch_enums',
    'PropertyId': 'kicad_sch_enums',
    'KiCadSchematic': 'kicad_schematic',
    'SchSymbol': 'kicad_sch_symbol',
    'SchWire': 'kicad_sch_wire',
    'SchBus': 'kicad_sch_wire',
    'SchBusEntry': 'kicad_sch_wire',
    'SchJunction': 'kicad_sch_junction',
    'SchNoConnect': 'kicad_sch_no_connect',
    'SchLabel': 'kicad_sch_label',
    'SchGlobalLabel': 'kicad_sch_label',
    'SchHierarchicalLabel': 'kicad_sch_label',
    'SchSheet': 'kicad_sch_sheet',
    'SchTextBox': 'kicad_sch_text_box',
    'TitleBlock': 'kicad_sch_title_block',
    'PaperSize': 'kicad_sch_title_block',
    'KiCadWorksheet': 'kicad_worksheet',
    'WksSetup': 'kicad_wks_primitives',
    'WksLine': 'kicad_wks_line',
    'WksRect': 'kicad_wks_rect',
    'WksPolygon': 'kicad_wks_polygon',
    'WksTbText': 'kicad_wks_text',
    'WksBitmap': 'kicad_wks_bitmap',
    'WksCorner': 'kicad_wks_primitives',
    'WksPoint': 'kicad_wks_primitives',
    'Footprint': 'kicad_pcb_footprint',
    'Pad': 'kicad_pad',
    'FpText': 'kicad_fp_text',
    'FpTextBox': 'kicad_fp_text_box',
    'FpLine': 'kicad_fp_line',
    'FpPoly': 'kicad_fp_poly',
    'Zone': 'kicad_pcb_zone',
    'Segment': 'kicad_pcb_routing',
    'Via': 'kicad_pcb_routing',
    'Arc': 'kicad_pcb_routing',
    'GrText': 'kicad_pcb_graphics',
    'GrLine': 'kicad_pcb_graphics',
    'GrRect': 'kicad_pcb_graphics',
    'GrArc': 'kicad_pcb_graphics',
    'GrCircle': 'kicad_pcb_graphics',
    'GrPoly': 'kicad_pcb_graphics',
    'GrCurve': 'kicad_pcb_graphics',
    'GrTextBox': 'kicad_pcb_graphics',
    'Layer': 'kicad_pcb_other',
    'Net': 'kicad_pcb_other',
    'NetRef': 'kicad_pcb_other',
    'OutlineCarrier': 'kicad_pcb_other',
    'BarcodeMargins': 'kicad_pcb_other',
    'Barcode': 'kicad_pcb_other',
    'DrillLayerSpan': 'kicad_pcb_other',
    'DrillProps': 'kicad_pcb_other',
    'PostMachiningProps': 'kicad_pcb_other',
    'ZoneLayerConnections': 'kicad_pcb_other',
    'PadNameGroup': 'kicad_pcb_other',
    'BoardVariant': 'kicad_pcb_other',
    'FootprintVariantField': 'kicad_pcb_other',
    'FootprintVariant': 'kicad_pcb_other',
    'FootprintPlacement': 'kicad_pcb_other',
    'ComponentClassRef': 'kicad_pcb_other',
    'GeneratedProperty': 'kicad_pcb_other',
    'GeneratedObject': 'kicad_pcb_other',
    'KiCadProject': 'kicad_project',
    'KiCadProjectBoardDesignSettings': 'kicad_project',
    'KiCadProjectDiffPairDimensions': 'kicad_project',
    'KiCadProjectNetClass': 'kicad_project',
    'KiCadProjectNetClassPattern': 'kicad_project',
    'KiCadProjectNetSettings': 'kicad_project',
    'KiCadProjectSidecar': 'kicad_project',
    'KiCadProjectTuningPatternDefaults': 'kicad_project',
    'KiCadProjectTuningPatternSettings': 'kicad_project',
    'ProjectVariant': 'kicad_project',
    'find_adjacent_kicad_project_path': 'kicad_project',
    'AssemblyComponent': 'kicad_variants',
    'EffectiveFootprintProperties': 'kicad_variants',
    'EffectiveSymbolProperties': 'kicad_variants',
    'VariantCatalog': 'kicad_variants',
    'VariantOverride': 'kicad_variants',
    'assemble': 'kicad_variants',
    'collect_footprint_overrides': 'kicad_variants',
    'collect_symbol_overrides': 'kicad_variants',
    'resolve_footprint': 'kicad_variants',
    'resolve_symbol': 'kicad_variants',
    'BoundingBox': 'kicad_geometry',
    'SvgRenderContext': 'kicad_geometry',
    'rotate_point': 'kicad_geometry',
    'SymbolTheme': 'kicad_symbol_svg',
    'SymbolSvgContext': 'kicad_symbol_svg',
    'SymbolRenderOptions': 'kicad_symbol_svg',
    'render_symbol_svg': 'kicad_symbol_svg',
    'render_library_svg': 'kicad_symbol_svg',
    'SchematicTheme': 'kicad_sch_svg',
    'SchematicSvgContext': 'kicad_sch_svg',
    'SchematicRenderOptions': 'kicad_sch_svg',
    'render_schematic_svg': 'kicad_sch_svg',
    'render_schematic_to_file': 'kicad_sch_svg',
    'read_kicad_pro_parameters': 'kicad_utilities',
    'make_kicad_httplib': 'kicad_utilities',
    'setup_kicad_preferences': 'kicad_utilities',
    'KICAD_PLOTTER_IR_SCHEMA': 'kicad_plotter_ir',
    'KiCadFillType': 'kicad_plotter_ir',
    'KiCadHorizAlign': 'kicad_plotter_ir',
    'KiCadLineStyle': 'kicad_plotter_ir',
    'KiCadPenAction': 'kicad_plotter_ir',
    'KiCadPlotterBounds': 'kicad_plotter_ir',
    'KiCadPlotterDocument': 'kicad_plotter_ir',
    'KiCadPlotterOp': 'kicad_plotter_ir',
    'KiCadPlotterOpKind': 'kicad_plotter_ir',
    'KiCadPlotterRecord': 'kicad_plotter_ir',
    'KiCadVertAlign': 'kicad_plotter_ir',
    'make_brush': 'kicad_plotter_ir',
    'make_font': 'kicad_plotter_ir',
    'make_pen': 'kicad_plotter_ir',
    'styled_plotter_op': 'kicad_plotter_ir',
    'KiCadJunctionZOrder': 'kicad_sch_svg_renderer',
    'KiCadSvgRenderContext': 'kicad_sch_svg_renderer',
    'KiCadSvgRenderOptions': 'kicad_sch_svg_renderer',
    'KiCadSvgRenderProfile': 'kicad_sch_svg_renderer',
    'KiCadVariantDimMode': 'kicad_sch_svg_renderer',
    'fmt_user_number': 'kicad_sch_svg_renderer',
    'svg_arc': 'kicad_sch_svg_renderer',
    'svg_bezier': 'kicad_sch_svg_renderer',
    'svg_circle': 'kicad_sch_svg_renderer',
    'svg_document': 'kicad_sch_svg_renderer',
    'svg_ellipse': 'kicad_sch_svg_renderer',
    'svg_group': 'kicad_sch_svg_renderer',
    'svg_line': 'kicad_sch_svg_renderer',
    'svg_path': 'kicad_sch_svg_renderer',
    'svg_polygon': 'kicad_sch_svg_renderer',
    'svg_polyline': 'kicad_sch_svg_renderer',
    'svg_rect': 'kicad_sch_svg_renderer',
    'svg_text': 'kicad_sch_svg_renderer',
    'svg_text_or_poly': 'kicad_sch_svg_renderer',
    'svg_text_poly': 'kicad_sch_svg_renderer',
    'SCHEMATIC_SVG_BLACK_AND_WHITE_ROLE_COLORS': 'kicad_schematic_style',
    'SCHEMATIC_SVG_COLOR_ROLES': 'kicad_schematic_style',
    'SCHEMATIC_SVG_ROLE_COLORS': 'kicad_schematic_style',
    'normalize_schematic_svg_color_role': 'kicad_schematic_style',
    'schematic_svg_role_color': 'kicad_schematic_style',
    'schematic_svg_role_color_overrides': 'kicad_schematic_style',
    'KiCadSvgPreferenceTheme': 'kicad_svg_preferences',
    'load_kicad_svg_preference_theme': 'kicad_svg_preferences',
    'schematic_svg_options_from_preferences': 'kicad_svg_preferences',
    'symbol_theme_from_preferences': 'kicad_svg_preferences',
    'arc_to_op': 'kicad_lib_symbol_to_ir',
    'bezier_to_op': 'kicad_lib_symbol_to_ir',
    'circle_to_op': 'kicad_lib_symbol_to_ir',
    'lib_symbol_to_ir': 'kicad_lib_symbol_to_ir',
    'mm_to_nm': 'kicad_lib_symbol_to_ir',
    'pin_to_ops': 'kicad_lib_symbol_to_ir',
    'polyline_to_op': 'kicad_lib_symbol_to_ir',
    'rectangle_to_op': 'kicad_lib_symbol_to_ir',
    'rgba_to_hex': 'kicad_lib_symbol_to_ir',
    'stroke_type_to_line_style': 'kicad_lib_symbol_to_ir',
    'stroke_width_nm': 'kicad_lib_symbol_to_ir',
    'subsymbol_to_record': 'kicad_lib_symbol_to_ir',
    'sym_fill_to_kicad_fill': 'kicad_lib_symbol_to_ir',
    'text_to_op': 'kicad_lib_symbol_to_ir',
    'y_to_ir': 'kicad_lib_symbol_to_ir',
    'DEFAULT_BUS_WIDTH_MM': 'kicad_schematic_to_ir',
    'DEFAULT_JUNCTION_DIAMETER_MM': 'kicad_schematic_to_ir',
    'DEFAULT_LABEL_SIZE_RATIO': 'kicad_schematic_to_ir',
    'DEFAULT_NO_CONNECT_HALF_MM': 'kicad_schematic_to_ir',
    'DEFAULT_TEXT_SIZE_MM': 'kicad_schematic_to_ir',
    'DEFAULT_WIRE_WIDTH_MM': 'kicad_schematic_to_ir',
    'bus_entry_to_op': 'kicad_schematic_to_ir',
    'bus_to_op': 'kicad_schematic_to_ir',
    'global_label_decoration_to_op': 'kicad_schematic_to_ir',
    'global_label_to_op': 'kicad_schematic_to_ir',
    'hierarchical_label_decoration_to_op': 'kicad_schematic_to_ir',
    'hierarchical_label_to_op': 'kicad_schematic_to_ir',
    'junction_to_op': 'kicad_schematic_to_ir',
    'label_to_op': 'kicad_schematic_to_ir',
    'no_connect_to_ops': 'kicad_schematic_to_ir',
    'paper_size_to_nm': 'kicad_schematic_to_ir',
    'sch_text_to_op': 'kicad_schematic_to_ir',
    'schematic_arc_to_ops': 'kicad_schematic_to_ir',
    'schematic_bezier_to_ops': 'kicad_schematic_to_ir',
    'schematic_circle_to_ops': 'kicad_schematic_to_ir',
    'schematic_image_to_op': 'kicad_schematic_to_ir',
    'schematic_polyline_to_ops': 'kicad_schematic_to_ir',
    'schematic_rectangle_to_ops': 'kicad_schematic_to_ir',
    'schematic_to_ir': 'kicad_schematic_to_ir',
    'sheet_background_to_op': 'kicad_schematic_to_ir',
    'sheet_outline_to_op': 'kicad_schematic_to_ir',
    'sheet_pin_decoration_to_op': 'kicad_schematic_to_ir',
    'sheet_pin_to_op': 'kicad_schematic_to_ir',
    'sheet_property_to_op': 'kicad_schematic_to_ir',
    'symbol_property_to_op': 'kicad_schematic_to_ir',
    'text_box_outline_to_op': 'kicad_schematic_to_ir',
    'text_box_to_ops': 'kicad_schematic_to_ir',
    'wire_to_op': 'kicad_schematic_to_ir',
    'render_ir_to_svg': 'kicad_ir_to_svg',
    'render_op': 'kicad_ir_to_svg',
    'render_record': 'kicad_ir_to_svg',
    'render_records': 'kicad_ir_to_svg',
    'KICAD_PLOTTER_RECORDER_SCHEMA': 'kicad_recorder_loader',
    'load_recorder_dict': 'kicad_recorder_loader',
    'load_recorder_file': 'kicad_recorder_loader',
    'normalise_recorder_op_units': 'kicad_recorder_loader',
    'translate_recorder_canvas': 'kicad_recorder_loader',
    'translate_recorder_op': 'kicad_recorder_loader',
    'KICAD_RECORDER_DRIFT_SCHEMA': 'kicad_recorder_drift',
    'RecorderDriftReport': 'kicad_recorder_drift',
    'compute_recorder_drift': 'kicad_recorder_drift',
    'STROKED_TEXT_FOLD_KIND': 'kicad_recorder_stroked_text_fold',
    'STROKED_TEXT_FOLD_MIN_POINTS': 'kicad_recorder_stroked_text_fold',
    'STROKED_TEXT_FOLD_MIN_RUN': 'kicad_recorder_stroked_text_fold',
    'fold_recorder_document': 'kicad_recorder_stroked_text_fold',
    'fold_stroked_text_runs': 'kicad_recorder_stroked_text_fold',
    'is_stroked_text_glyph': 'kicad_recorder_stroked_text_fold',
    'KICAD_OP_EQUIVALENCE_SCHEMA': 'kicad_op_equivalence',
    'MATCH_STRATEGY_BY_KIND': 'kicad_op_equivalence',
    'MATCH_STRATEGY_POSITIONAL': 'kicad_op_equivalence',
    'MATCH_STRATEGY_WINDOWED_BY_KIND': 'kicad_op_equivalence',
    'MATCH_WINDOW_UNBOUNDED': 'kicad_op_equivalence',
    'KiCadOpDivergence': 'kicad_op_equivalence',
    'OpEquivalenceReport': 'kicad_op_equivalence',
    'compute_op_equivalence': 'kicad_op_equivalence',
    'KiCadPlotterTransform2D': 'kicad_plotter_transform',
    'apply_transform_to_op': 'kicad_plotter_transform',
    'apply_transform_to_ops': 'kicad_plotter_transform',
    'transform_orient': 'kicad_plotter_transform',
    'transform_point': 'kicad_plotter_transform',
    'DEFAULT_KICAD_WKS': 'kicad_drawing_sheet',
    'drawing_sheet_to_ops': 'kicad_drawing_sheet',
    'expand_format_codes': 'kicad_drawing_sheet',
    'load_default_drawing_sheet': 'kicad_drawing_sheet',
    'KiCadDesign': 'kicad_design',
    'KiCadSchematicInstance': 'kicad_design',
    'footprint_to_ir': 'kicad_footprint_to_ir',
    'footprint_to_record': 'kicad_footprint_to_ir',
    'fp_arc_to_op': 'kicad_footprint_to_ir',
    'fp_circle_to_op': 'kicad_footprint_to_ir',
    'fp_fill_to_kicad_fill': 'kicad_footprint_to_ir',
    'fp_line_to_op': 'kicad_footprint_to_ir',
    'fp_poly_to_op': 'kicad_footprint_to_ir',
    'fp_rect_to_op': 'kicad_footprint_to_ir',
    'fp_text_box_to_ops': 'kicad_footprint_to_ir',
    'fp_text_to_op': 'kicad_footprint_to_ir',
    'pad_drill_to_ops': 'kicad_footprint_to_ir',
    'pad_to_ops': 'kicad_footprint_to_ir',
    'property_to_op': 'kicad_footprint_to_ir',
    'KiCadVariantOverlayPolicy': 'kicad_variant_overlay',
    'VARIANT_STATE_ACTIVE': 'kicad_variant_overlay',
    'VARIANT_STATE_DIMMED': 'kicad_variant_overlay',
    'VARIANT_STATE_KEY': 'kicad_variant_overlay',
    'annotate_record_variant_state': 'kicad_variant_overlay',
    'apply_variant_overlay': 'kicad_variant_overlay',
    'compute_record_variant_state': 'kicad_variant_overlay',
    'pcb_to_ir': 'kicad_pcb_to_ir',
    'gr_line_to_op': 'kicad_pcb_to_ir',
    'gr_line_to_record': 'kicad_pcb_to_ir',
    'gr_arc_to_op': 'kicad_pcb_to_ir',
    'gr_arc_to_record': 'kicad_pcb_to_ir',
    'gr_circle_to_op': 'kicad_pcb_to_ir',
    'gr_circle_to_record': 'kicad_pcb_to_ir',
    'gr_rect_to_op': 'kicad_pcb_to_ir',
    'gr_rect_to_record': 'kicad_pcb_to_ir',
    'gr_poly_to_op': 'kicad_pcb_to_ir',
    'gr_poly_to_record': 'kicad_pcb_to_ir',
    'gr_curve_to_op': 'kicad_pcb_to_ir',
    'gr_curve_to_record': 'kicad_pcb_to_ir',
    'gr_text_to_op': 'kicad_pcb_to_ir',
    'gr_text_to_record': 'kicad_pcb_to_ir',
    'gr_text_box_to_ops': 'kicad_pcb_to_ir',
    'gr_text_box_to_record': 'kicad_pcb_to_ir',
    'track_segment_to_op': 'kicad_pcb_to_ir',
    'track_segment_to_record': 'kicad_pcb_to_ir',
    'track_arc_to_op': 'kicad_pcb_to_ir',
    'track_arc_to_record': 'kicad_pcb_to_ir',
    'via_drill_to_op': 'kicad_pcb_to_ir',
    'via_to_op': 'kicad_pcb_to_ir',
    'via_to_record': 'kicad_pcb_to_ir',
    'zone_filled_polygon_to_op': 'kicad_pcb_to_ir',
    'zone_to_record': 'kicad_pcb_to_ir',
    'pcb_footprint_to_record': 'kicad_pcb_to_ir',
    'render_pcb_ir_to_svg': 'kicad_pcb_ir_svg',
    'SCH_IU_PER_MM': 'kicad_schematic_connectivity',
    'snap_mm_to_iu': 'kicad_schematic_connectivity',
    'iu_key_to_mm': 'kicad_schematic_connectivity',
    'compute_pin_position': 'kicad_schematic_connectivity',
    'iter_symbol_pins': 'kicad_schematic_connectivity',
    'CoordinateIndex': 'kicad_schematic_connectivity',
    'ConnectivityGraph': 'kicad_schematic_connectivity',
    'detect_no_connects': 'kicad_schematic_connectivity',
    'is_bus_label': 'kicad_bus_expansion',
    'parse_bus_vector': 'kicad_bus_expansion',
    'parse_bus_group': 'kicad_bus_expansion',
    'expand_bus_label': 'kicad_bus_expansion',
    'KiCadDriverPriority': 'kicad_netlist_model',
    'KiCadDriverKind': 'kicad_netlist_model',
    'KiCadPinType': 'kicad_netlist_model',
    'KiCadNetlistTerminal': 'kicad_netlist_model',
    'KiCadNetEndpoint': 'kicad_netlist_model',
    'KiCadNet': 'kicad_netlist_model',
    'KiCadNetlistComponent': 'kicad_netlist_model',
    'KiCadLibPart': 'kicad_netlist_model',
    'KiCadLibPartPin': 'kicad_netlist_model',
    'KiCadDesignSheet': 'kicad_netlist_model',
    'KiCadDesignMetadata': 'kicad_netlist_model',
    'KiCadNetlist': 'kicad_netlist_model',
    'Subgraph': 'kicad_netlist_compiler',
    'compile_sheet_subgraphs': 'kicad_netlist_compiler',
    'compile_sheet_netlist': 'kicad_netlist_compiler',
    'name_net': 'kicad_netlist_compiler',
    'CompiledSheet': 'kicad_netlist_design',
    'compile_design_subgraphs': 'kicad_netlist_design',
    'merge_design_nets': 'kicad_netlist_design',
    'compile_design_netlist': 'kicad_netlist_design',
    'collect_design_components': 'kicad_netlist_design',
    'collect_design_libparts': 'kicad_netlist_design',
    'KICAD_NETLIST_VERSION': 'kicad_netlist_kicadsexpr',
    'to_kicad_sexpr': 'kicad_netlist_kicadsexpr',
}


def __getattr__(name: str) -> Any:
    """Lazy import for modules with external dependencies."""
    module_name = _LAZY_EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f".{module_name}", __name__), name)
    globals()[name] = value
    return value
