"""Named KiCad file-format defaults used by the public OOP models."""

from __future__ import annotations

KICAD_SCHEMATIC_FILE_VERSION = 20260306
KICAD_SYMBOL_LIB_FILE_VERSION = 20251024
KICAD_PCB_FILE_VERSION = 20260206
KICAD_FOOTPRINT_FILE_VERSION = 20260206

KICAD_SCHEMATIC_GENERATOR = "eeschema"
KICAD_SYMBOL_LIB_GENERATOR = "kicad_symbol_editor"
KICAD_PCB_GENERATOR = "pcbnew"
KICAD_FOOTPRINT_GENERATOR = "pcbnew"
KICAD_GENERATOR_VERSION = "10.0"

KICAD_DEFAULT_BOARD_THICKNESS_MM = 1.6
KICAD_DEFAULT_PAPER = "A4"
KICAD_DEFAULT_PIN_NAME_OFFSET_MM = 0.508
KICAD_DEFAULT_SHEET_WIDTH_MM = 50.8
KICAD_DEFAULT_SHEET_HEIGHT_MM = 35.56
KICAD_DEFAULT_TEXT_SIZE_MM = 1.27

__all__ = [
    "KICAD_DEFAULT_BOARD_THICKNESS_MM",
    "KICAD_DEFAULT_PAPER",
    "KICAD_DEFAULT_PIN_NAME_OFFSET_MM",
    "KICAD_DEFAULT_SHEET_HEIGHT_MM",
    "KICAD_DEFAULT_SHEET_WIDTH_MM",
    "KICAD_DEFAULT_TEXT_SIZE_MM",
    "KICAD_FOOTPRINT_FILE_VERSION",
    "KICAD_FOOTPRINT_GENERATOR",
    "KICAD_GENERATOR_VERSION",
    "KICAD_PCB_FILE_VERSION",
    "KICAD_PCB_GENERATOR",
    "KICAD_SCHEMATIC_FILE_VERSION",
    "KICAD_SCHEMATIC_GENERATOR",
    "KICAD_SYMBOL_LIB_FILE_VERSION",
    "KICAD_SYMBOL_LIB_GENERATOR",
]
