#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SchematicBundleLimits {
    pub max_source_bytes: usize,
    pub max_depth: usize,
    pub max_selected_forms_per_source: usize,
    pub max_sheets_per_source: usize,
    pub max_sheet_properties: usize,
    pub max_sheet_pins_per_sheet: usize,
    pub max_symbols_per_source: usize,
    pub max_symbol_properties_per_symbol: usize,
    pub max_symbol_pins_per_symbol: usize,
    pub max_library_symbols_per_source: usize,
    pub max_library_subsymbols_per_source: usize,
    pub max_library_pins_per_source: usize,
    pub max_library_lookup_key_bytes_per_source: usize,
    pub max_symbol_terminals_per_occurrence: usize,
    pub max_symbol_terminal_retained_bytes_per_occurrence: usize,
    pub max_symbol_instance_projects_per_symbol: usize,
    pub max_symbol_instances_per_symbol: usize,
    pub max_symbol_instance_index_bytes_per_source: usize,
    pub max_symbol_variants_per_instance: usize,
    pub max_symbol_variant_fields_per_variant: usize,
    pub max_legacy_symbol_instances_per_source: usize,
    pub max_decoded_string_bytes: usize,
    pub max_connectivity_objects_per_source: usize,
    pub max_wires_per_source: usize,
    pub max_buses_per_source: usize,
    pub max_bus_entries_per_source: usize,
    pub max_bus_aliases_per_source: usize,
    pub max_bus_alias_members_per_source: usize,
    pub max_junctions_per_source: usize,
    pub max_no_connects_per_source: usize,
    pub max_labels_per_source: usize,
    pub max_points_per_connectivity_object: usize,
    pub max_connectivity_points_per_source: usize,
    pub max_occurrences: usize,
    pub max_path_bytes: usize,
}

impl Default for SchematicBundleLimits {
    fn default() -> Self {
        Self {
            max_source_bytes: 512 * 1024 * 1024,
            max_depth: 512,
            max_selected_forms_per_source: 4_000_000,
            max_sheets_per_source: 1_000_000,
            max_sheet_properties: 1_000_000,
            max_sheet_pins_per_sheet: 1_000_000,
            max_symbols_per_source: 4_000_000,
            max_symbol_properties_per_symbol: 1_000_000,
            max_symbol_pins_per_symbol: 1_000_000,
            max_library_symbols_per_source: 1_000_000,
            max_library_subsymbols_per_source: 4_000_000,
            max_library_pins_per_source: 8_000_000,
            max_library_lookup_key_bytes_per_source: 64 * 1024 * 1024,
            max_symbol_terminals_per_occurrence: 8_000_000,
            max_symbol_terminal_retained_bytes_per_occurrence: 512 * 1024 * 1024,
            max_symbol_instance_projects_per_symbol: 1_000_000,
            max_symbol_instances_per_symbol: 1_000_000,
            max_symbol_instance_index_bytes_per_source: 512 * 1024 * 1024,
            max_symbol_variants_per_instance: 1_000_000,
            max_symbol_variant_fields_per_variant: 1_000_000,
            max_legacy_symbol_instances_per_source: 4_000_000,
            max_decoded_string_bytes: 64 * 1024 * 1024,
            max_connectivity_objects_per_source: 4_000_000,
            max_wires_per_source: 4_000_000,
            max_buses_per_source: 4_000_000,
            max_bus_entries_per_source: 4_000_000,
            max_bus_aliases_per_source: 1_000_000,
            max_bus_alias_members_per_source: 8_000_000,
            max_junctions_per_source: 4_000_000,
            max_no_connects_per_source: 4_000_000,
            max_labels_per_source: 4_000_000,
            max_points_per_connectivity_object: 1_000_000,
            max_connectivity_points_per_source: 8_000_000,
            max_occurrences: 4_000_000,
            max_path_bytes: 32 * 1024,
        }
    }
}
