"""Generate the compact Rust Newstroke advance-width table."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "py" / "kicad_monkey" / "kicad_stroke_font_data.json"
TARGET = (
    ROOT
    / "src"
    / "rs"
    / "kicad-monkey-core"
    / "src"
    / "board_plotter_ir"
    / "stroke_font_widths.rs"
)


def generated() -> bytes:
    glyphs = json.loads(SOURCE.read_text(encoding="utf-8"))
    widths = [ord(glyph[1]) - ord(glyph[0]) if len(glyph) >= 2 else 0 for glyph in glyphs]
    offsets = [0]
    for glyph in glyphs:
        offsets.append(offsets[-1] + len(glyph))
    glyph_data = "".join(glyphs)
    lines = [
        "// Generated by scripts/generate_stroke_font_widths.py; do not edit.\n",
        "#[rustfmt::skip]\n",
        f"pub(super) const NEWSTROKE_WIDTH_UNITS: [u8; {len(widths)}] = [\n",
    ]
    for offset in range(0, len(widths), 24):
        chunk = ", ".join(str(value) for value in widths[offset : offset + 24])
        lines.append(f"    {chunk},\n")
    lines.append("];\n")
    lines.extend([
        "\n#[rustfmt::skip]\n",
        "pub(super) const NEWSTROKE_GLYPH_DATA: &str = concat!(\n",
    ])
    for offset in range(0, len(glyph_data), 4096):
        chunk = glyph_data[offset : offset + 4096]
        lines.append(f"    {json.dumps(chunk, ensure_ascii=True)},\n")
    lines.extend([
        ");\n",
        "\n#[rustfmt::skip]\n",
        f"pub(super) static NEWSTROKE_GLYPH_OFFSETS: [u32; {len(offsets)}] = [\n",
    ])
    for offset in range(0, len(offsets), 16):
        chunk = ", ".join(str(value) for value in offsets[offset : offset + 16])
        lines.append(f"    {chunk},\n")
    lines.append("];\n")
    return "".join(lines).encode()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = generated()
    if args.check:
        if not TARGET.exists() or TARGET.read_bytes() != output:
            raise SystemExit(f"stale stroke-font widths: {TARGET}")
        return
    TARGET.write_bytes(output)
    print(f"wrote {TARGET.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
