r"""Driver for the Phase 2+ KiCad synthetic corpus generators.

Walks every family generator in ``synthetic_corpus/`` (or a subset with
``--family``) and writes per-case fixtures into
``<corpus>/kicad/pcb_foundation/<case_id>/input/``.

Reference SVGs are NOT generated by this driver — run
the package-local SVG reference generator afterward if reference outputs are
needed.

Examples::

    # Dry-run every family.
    uv run python kicad_monkey/scripts/generate_kicad_synthetic_corpus.py --dry-run

    # Write tracks only, overwriting existing files.
    uv run python kicad_monkey/scripts/generate_kicad_synthetic_corpus.py \
        --family tracks --force

    # Just case011.
    uv run python kicad_monkey/scripts/generate_kicad_synthetic_corpus.py \
        --case case011__pad_smd_rect --force
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Iterable

from synthetic_corpus import (
    CaseSpec,
    write_case_artifacts,
)
from synthetic_corpus.generate_arcs import CASES as ARC_CASES
from synthetic_corpus.generate_fills import CASES as FILL_CASES
from synthetic_corpus.generate_pads import CASES as PAD_CASES
from synthetic_corpus.generate_text import CASES as TEXT_CASES
from synthetic_corpus.generate_text_frames import CASES as TEXT_FRAME_CASES
from synthetic_corpus.generate_tracks import CASES as TRACK_CASES
from synthetic_corpus.generate_vias import CASES as VIA_CASES

REPO_ROOT = Path(__file__).resolve().parents[1]


# Family name → spec tuple. Drives ``--family`` selection and the
# default iteration order when the user passes no filter.
FAMILY_CASES: dict[str, tuple[CaseSpec, ...]] = {
    "tracks": TRACK_CASES,
    "arcs": ARC_CASES,
    "pads": PAD_CASES,
    "vias": VIA_CASES,
    "fills": FILL_CASES,
    "text": TEXT_CASES,
    "text_frames": TEXT_FRAME_CASES,
}


def _iter_specs(
    families: Iterable[str],
    *,
    case_ids: set[str] | None,
) -> list[tuple[str, CaseSpec]]:
    out: list[tuple[str, CaseSpec]] = []
    for family in families:
        for spec in FAMILY_CASES[family]:
            if case_ids and spec.case_id not in case_ids:
                continue
            out.append((family, spec))
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--corpus-root",
        type=Path,
        default=REPO_ROOT / "tests" / "corpus",
        help="Writable authoring root containing kicad/pcb_foundation/.",
    )
    parser.add_argument(
        "--family",
        action="append",
        choices=sorted(FAMILY_CASES.keys()),
        help="Restrict to a family; may be repeated. Default: all.",
    )
    parser.add_argument(
        "--case",
        action="append",
        default=None,
        help="Restrict to specific case_id(s); may be repeated.",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="List the planned cases and exit (implies --dry-run).",
    )
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    families = args.family or sorted(FAMILY_CASES.keys())
    case_ids = set(args.case) if args.case else None

    specs = _iter_specs(families, case_ids=case_ids)
    if not specs:
        print("No matching cases for the given family/case filter.", file=sys.stderr)
        return 2

    if args.list:
        for family, spec in specs:
            print(f"{family:8s} {spec.case_id}  -- {spec.description}")
        return 0

    written_total = 0
    for family, spec in specs:
        paths = write_case_artifacts(
            args.corpus_root,
            spec,
            force=args.force,
            dry_run=args.dry_run,
        )
        action = "Would write" if args.dry_run else "Wrote"
        for path in paths:
            print(f"{action} [{family}] {path}")
        written_total += len(paths)

    print(
        f"\n{'Planned' if args.dry_run else 'Wrote'} {written_total} files "
        f"across {len(specs)} cases.",
        file=sys.stderr,
    )
    if not args.dry_run:
        print(
            "\nNext: regenerate reference SVGs via "
            "the package-local SVG reference generator if needed.",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
