"""Mirror KiCad upstream-QA netlist fixtures into the test corpus.

Phase G - Slice N-8. Copies discovered KiCad 9/10-format test cases from
``<kicad_src>/qa/data/eeschema/netlists/<case>/`` into
``<corpus>/kicad/netlist/upstream_qa/<case>/``. Each case directory
carries the source schematic(s), an optional ``.kicad_pro``, and the
golden ``.net`` produced by upstream's own KiCad build at the time the
fixture was committed.

Usage::

    python scripts/sync_upstream_qa_netlist_fixtures.py
        --kicad-src <local KiCad source checkout>
        [--corpus "<writable corpus authoring root>"]
        [--dry-run]

Mirrors the conventions of ``sync_upstream_qa_fixtures.py``: SHA-256 +
provenance manifest under ``<dest>/MANIFEST.toml``. Re-run after pulling
the upstream fork.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


MIN_SUPPORTED_SCHEMATIC_VERSION = 20240716


def _top_schematic_for_case(case_dir: Path) -> Path | None:
    """Return the likely top schematic for a netlist QA case."""
    candidate = case_dir / f"{case_dir.name}.kicad_sch"
    if candidate.is_file():
        return candidate
    schs = sorted(case_dir.glob("*.kicad_sch"))
    return schs[0] if schs else None


def _schematic_file_format_version(path: Path) -> int | None:
    """Read the ``(version N)`` header from a ``.kicad_sch`` file."""
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines()[:12]:
        stripped = line.strip()
        if stripped.startswith("(version ") and stripped.endswith(")"):
            value = stripped.removeprefix("(version ").removesuffix(")")
            return int(value) if value.isdigit() else None
    return None


def _discover_cases(kicad_src: Path) -> list[str]:
    """Return all upstream eeschema/netlists case directory names.

    Mirroring the whole directory keeps multi-sheet hierarchies intact. Legacy
    ``.sch``-only cases and old ``.kicad_sch`` file-format cases are
    intentionally excluded; kicad_monkey's supported schematic format lane is
    KiCad 9/10.
    """
    netlists_dir = kicad_src / "qa" / "data" / "eeschema" / "netlists"
    if not netlists_dir.is_dir():
        raise SystemExit(f"Upstream netlist fixture directory not found: {netlists_dir}")
    cases: list[str] = []
    for case_dir in sorted(p for p in netlists_dir.iterdir() if p.is_dir()):
        top_schematic = _top_schematic_for_case(case_dir)
        if top_schematic is None:
            continue
        version = _schematic_file_format_version(top_schematic)
        if version is not None and version >= MIN_SUPPORTED_SCHEMATIC_VERSION:
            cases.append(case_dir.name)
    return cases


@dataclass
class CopyRecord:
    src_rel: str
    dst_rel: str
    bytes: int
    sha256: str


def _git_head_sha(repo: Path) -> str:
    out = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=repo, check=True, capture_output=True, text=True,
    )
    return out.stdout.strip()


def _git_short(repo: Path) -> str:
    out = subprocess.run(
        ["git", "log", "-1", "--format=%h %ai %s"],
        cwd=repo, check=True, capture_output=True, text=True,
    )
    return out.stdout.strip()


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _resolve_corpus(arg: Path | None) -> Path:
    if arg:
        return arg
    return REPO_ROOT / "tests" / "corpus"


def _toml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _write_manifest(
    *,
    manifest_path: Path,
    kicad_src: Path,
    sha: str,
    short: str,
    copied_at: str,
    records: list[CopyRecord],
) -> None:
    lines: list[str] = []
    lines.append("# Auto-generated by sync_upstream_qa_netlist_fixtures.py")
    lines.append("# Refresh by re-running the script after pulling the KiCad fork.")
    lines.append("")
    lines.append("[provenance]")
    lines.append(f'kicad_source_root = {_toml_quote(str(kicad_src))}')
    lines.append(f'kicad_commit_sha  = {_toml_quote(sha)}')
    lines.append(f'kicad_commit_log  = {_toml_quote(short)}')
    lines.append(f'copied_at_utc     = {_toml_quote(copied_at)}')
    lines.append(
        'license = "GPL-2.0-or-later (inherited from KiCad). Files retain their upstream license."'
    )
    lines.append(f'fixture_count = {len(records)}')
    lines.append("")
    for rec in records:
        lines.append("[[file]]")
        lines.append(f'src_rel = {_toml_quote(rec.src_rel)}')
        lines.append(f'dst_rel = {_toml_quote(rec.dst_rel)}')
        lines.append(f'bytes   = {rec.bytes}')
        lines.append(f'sha256  = {_toml_quote(rec.sha256)}')
        lines.append("")
    manifest_path.write_text("\n".join(lines), encoding="utf-8")


def _walk_case_files(case_dir: Path) -> list[Path]:
    """Return all regular files in case_dir (non-recursive — case dirs
    are flat in upstream qa, but we collect everything to stay future-
    proof against nested layouts)."""
    out = []
    for p in sorted(case_dir.rglob("*")):
        if p.is_file():
            out.append(p)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--kicad-src", type=Path,
        default=None,
        help="Path to the local KiCad source checkout.",
    )
    parser.add_argument(
        "--corpus", type=Path, default=None,
        help="Writable corpus authoring root (defaults to tests/corpus).",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Print actions but do not copy or write the manifest.",
    )
    args = parser.parse_args(argv)

    if args.kicad_src is None:
        raise SystemExit("--kicad-src is required")
    kicad_src: Path = args.kicad_src.resolve()
    if not (kicad_src / ".git").exists():
        print(f"Not a git checkout: {kicad_src}", file=sys.stderr)
        return 2

    cases = _discover_cases(kicad_src)
    corpus = _resolve_corpus(args.corpus).resolve()
    upstream_qa = corpus / "kicad" / "netlist" / "upstream_qa"

    sha = _git_head_sha(kicad_src)
    short = _git_short(kicad_src)
    copied_at = dt.datetime.now(dt.timezone.utc).isoformat()

    print(f"KiCad source : {kicad_src}")
    print(f"KiCad HEAD   : {short}")
    print(f"Corpus root  : {corpus}")
    print(f"Mirror dest  : {upstream_qa}")
    print(f"Cases        : {len(cases)}")
    print(f"Mode         : {'DRY-RUN' if args.dry_run else 'COPY'}")
    print()

    records: list[CopyRecord] = []
    missing: list[str] = []
    for case in cases:
        case_src = kicad_src / "qa" / "data" / "eeschema" / "netlists" / case
        if not case_src.is_dir():
            missing.append(case)
            print(f"  [MISSING] {case}")
            continue
        for f in _walk_case_files(case_src):
            rel = f.relative_to(case_src)
            src_rel = f"qa/data/eeschema/netlists/{case}/{rel.as_posix()}"
            dst_rel = f"{case}/{rel.as_posix()}"
            dst = upstream_qa / dst_rel
            size = f.stat().st_size
            digest = _sha256(f)
            if not args.dry_run:
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(f, dst)
            records.append(CopyRecord(src_rel=src_rel, dst_rel=dst_rel,
                                      bytes=size, sha256=digest))
            print(f"  {'(would copy)' if args.dry_run else 'copied'}  {case}/{rel.as_posix()}  ({size} bytes)")

    if missing:
        print(f"\n{len(missing)} case(s) not found at the expected upstream path.")
        for m in missing:
            print(f"  - {m}")

    manifest_path = upstream_qa / "MANIFEST.toml"
    if not args.dry_run:
        upstream_qa.mkdir(parents=True, exist_ok=True)
        _write_manifest(
            manifest_path=manifest_path,
            kicad_src=kicad_src,
            sha=sha,
            short=short,
            copied_at=copied_at,
            records=records,
        )
        print(f"\nWrote {manifest_path}")
    else:
        print(f"\n(dry-run) would write manifest at {manifest_path}")

    return 0 if not missing else 1


if __name__ == "__main__":
    sys.exit(main())
